name: Build and deploy ASP.Net Core app to Azure Web App - StarWarsLegionArmyBuilder-WebApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build StarWarsLegionArmyBuilder/StarWarsLegionWebApp/StarWarsLegionWebApp.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish StarWarsLegionArmyBuilder/StarWarsLegionWebApp/StarWarsLegionWebApp.csproj -c Release -o ./myapp

      - name: dotnet workload list
        run: dotnet workload list

      - name: List contents of publish directory (debugging)
        run: |
          echo "Listing contents of publish folder:"
          dir ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Find the downloaded artifact .zip file
        run: |
          echo "Searching for .zip files in the _temp directory:"
          Get-ChildItem -Path D:\a\_temp -Recurse -Filter *.zip

      - name: Extract artifact
        run: |
          echo "Extracting the artifact"
          Expand-Archive -Path D:\a\_temp\fa3fde4f1f5429467501ccd7f3e0425a0c429d3e8dedb5fba065de41de410abf.zip -DestinationPath D:\a\_temp\.net-app

      - name: List contents of the _temp directory (debugging)
        run: |
          echo "Listing contents of _temp directory:"
          dir D:\a\_temp


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_14DC29DCD9834DB3951D61D3EC72265E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89D61E7C28AB46B6AB8FC8FB6F1360E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_304AEF9CB1284A518734560B2636F31F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'StarWarsLegionArmyBuilder-WebApp'
          slot-name: 'Production'
          package: D:\a\_temp\.net-app
